/** English locale */
export const en = {
 meta: {
 homeTitle: "Amigura | Handmade Amigurumi Collection",
 homeDesc:
 "Amigura - Luxury handmade amigurumi in organic yarn. Order safely on Trendyol.",
 ozelTitle: "Custom Order | Amigura",
 ozelDesc: "Design your dream amigurumi in a 4-step custom order wizard.",
 thanksTitle: "Thank You | Amigura",
 thanksDesc: "Thank you for your order. Care tips and how to follow us.",
 kvkkTitle: "Privacy Policy | Amigura",
 iadeTitle: "Returns & Cancellation | Amigura",
 },
 nav: {
 collection: "Collection",
 custom: "Custom Order",
 about: "About",
 contact: "Contact",
 home: "Amigura - Home",
 brandTagline: "Handmade Atelier",
 openMenu: "Open menu",
 closeMenu: "Close menu",
 menuLabel: "Main menu",
 menuMobile: "Mobile menu",
 },
 theme: { toDark: "Dark theme", toLight: "Light theme", light: "Light", dark: "Dark" },
 lang: { label: "Language", tr: "Turkish", en: "English" },
 a11y: { skip: "Skip to content" },
 hero: {
 eyebrow: "Amigura - Handmade Art",
 title: "Love, Stitch by Stitch",
 subtitle:
 "Each figure is a warm touch, patiently crocheted. Discover the finest handcraft in our bespoke amigurumi collection.",
 cta: "Explore Collection",
 ctaAria: "Browse the amigurumi collection",
 },
 trust: {
 label: "Trust and quality",
 handmade: "Handmade",
 organic: "Organic yarn",
 trendyol: "Secure Trendyol checkout",
 kvkk: "Privacy compliant",
 },
 products: {
 sectionLabel: "Product collection",
 eyebrow: "Collection",
 title: "Carefully Crocheted Pieces",
 lead:
 "Four iconic wizarding-world characters, crocheted stitch by stitch. Pick your favourite and order safely on Trendyol.",
 harryPotter: {
 name: "Harry Potter Amigurumi",
 desc: "Round glasses, Gryffindor scarf and star-embroidered hat - the beloved wizard.",
 price: "549 TRY",
 careWash: "Cold wash (30C), mild detergent.",
 careSize: "Approx. 18 cm sitting.",
 careSafety: "Safe embroidered eyes; suitable under 3 with supervision.",
 },
 hermione: {
 name: "Hermione Granger Amigurumi",
 desc: "Brown curly hair, Hogwarts uniform and wand detail - the clever hero.",
 price: "529 TRY",
 careWash: "Cold wash, lay flat to dry.",
 careSize: "Approx. 17 cm sitting.",
 careSafety: "Organic cotton yarn; hand-embroidered details.",
 },
 malefiz: {
 name: "Maleficent Amigurumi",
 desc: "Black cape, horned headpiece and purple accents - a striking villain.",
 price: "579 TRY",
 careWash: "Cold wash, lay flat to dry.",
 careSize: "Approx. 19 cm (with headpiece).",
 careSafety: "Limited edition; quality-controlled handcraft.",
 },
 ronald: {
 name: "Ronald Weasley Amigurumi",
 desc: "Ginger hair, Gryffindor jumper and a warm loyal expression.",
 price: "499 TRY",
 careWash: "Cold wash, lay flat to dry.",
 careSize: "Approx. 17 cm sitting.",
 careSafety: "Secure stitching and embroidered eyes.",
 },
 },
 product: {
 buy: "Buy on Trendyol",
 buyGift: "Send as Gift",
 care: "Care & Size",
 intentLabel: "Purchase intent",
 intentSelf: "For Myself",
 intentGift: "Gift",
 giftTip: "Gift wrapping available",
 buyAria: "Buy {name} on Trendyol",
 buyGiftAria: "Send {name} as gift on Trendyol",
 careAria: "{name} care and size guide",
 alt: "{name} - handmade Amigura amigurumi",
 },
 status: { inStock: "In Stock", custom7: "Custom - 7 Days", limited: "Limited - 2 Left" },
 atelier: {
 eyebrow: "From the Studio",
 title: "Latest Studio Posts",
 region: "Studio photo gallery",
 cta: "Follow on Instagram",
 viewOnIg: "{alt} - view on Instagram",
 post1: "Organic yarn skein in the studio",
 post2: "Hand-crocheted amigurumi work in progress",
 post3: "Hook and yarn detail",
 post4: "Gift wrap preparation",
 post5: "Pastel yarn colour palette",
 post6: "Finished amigurumi figure",
 },
 reviews: {
 eyebrow: "Happy Hands",
 title: "What Our Buyers Say",
 dots: "Review slides",
 verified: "Verified Trendyol buyer",
 dotAria: "Review {n}",
 r1: {
 quote:
 "My daughter hugs it every night. The texture is so different from store toys - warm and soft.",
 name: "Elif K.",
 city: "Istanbul",
 product: "Harry Potter Amigurumi",
 },
 r2: {
 quote:
 "Bought it as a birthday gift. Beautiful packaging - felt boutique even though I ordered on Trendyol.",
 name: "Mert A.",
 city: "Ankara",
 product: "Hermione Granger Amigurumi",
 },
 r3: {
 quote:
 "Maleficent's horns and cape are stunning even in photos. It sits proudly in our display cabinet.",
 name: "Zeynep D.",
 city: "Izmir",
 product: "Maleficent Amigurumi",
 },
 r4: {
 quote:
 "We chose it for safe embroidered eyes for our 3-year-old. Ronald was exactly what we hoped for.",
 name: "Ayse T.",
 city: "Bursa",
 product: "Ronald Weasley Amigurumi",
 },
 r5: {
 quote:
 "We got the Harry and Hermione pair - colour harmony and craft are excellent. Lovely gift note, thank you Irem.",
 name: "Can Y.",
 city: "Antalya",
 product: "Harry Potter Amigurumi",
 },
 },
 process: {
 eyebrow: "Stitch by Stitch",
 title: "From Studio to Your Story",
 lead: "Every figure goes through four careful stages. Follow the journey of handcraft below.",
 s1title: "Yarn Selection",
 s1text:
 "Premium organic cotton yarns are chosen one by one; colour and texture match your figure's character.",
 s2title: "Crocheting",
 s2text:
 "Each piece starts with a magic ring and takes shape stitch by stitch in Irem's hands - patience and rhythm come alive.",
 s3title: "Details",
 s3text:
 "Safe eyes, nose and accessories; every seam is quality-checked for a flawless expression.",
 s4title: "Packaging",
 s4text:
 "Your figure is wrapped in careful gift packaging and checked with love once more before shipping.",
 },
 about: {
 eyebrow: "Amigura",
 titleLine1: "A Dream in Every Stitch,",
 titleAccent: "Love in Every Touch",
 lead:
 "Amigura is a design studio that champions the warmth of handcraft and organic fibres against mass production.",
 text:
 "Every amigurumi crocheted by founder Irem with premium organic cotton is more than a toy - safe for your children and a memory for you. We bring nature and wonder home.",
 imgAlt: "Amigura studio — handmade amigurumi",
 },
 newsletter: {
 eyebrow: "Stitch Newsletter",
 title: "Be first to discover new collections",
 lead: "Studio stories, launches and custom order slots - once a month, simple and warm.",
 emailLabel: "Your email address",
 placeholder: "you@example.com",
 submit: "Subscribe",
 success: "Thank you! We'll be in your inbox with our first newsletter.",
 mailtoSubject: "Amigura newsletter signup",
 mailtoBody: "Please add me to the newsletter list. Email: {email}",
 },
 contact: {
 heading: "Contact",
 eyebrow: "Get in Touch",
 lead: "Questions about the collection, custom orders or collaborations - we'd love to hear from you.",
 },
 footer: {
 socialNav: "Social and contact links",
 legalNav: "Legal information",
 email: "Email",
 kvkk: "Privacy Policy",
 returns: "Returns & Cancellation",
 copy: "2026 Amigura. All rights reserved.",
 },
 modal: {
 close: "Close dialog",
 handoffTitle: "Redirecting to Trendyol",
 handoffLoading: "Redirecting you to Trendyol's secure checkout...",
 handoffLead:
 "Your order completes on Trendyol's secure platform. Amigura is responsible for packaging and quality.",
 handoffLi1: "Secure payment with 256-bit SSL",
 handoffLi2: "Trendyol buyer protection",
 handoffLi3: "Easy returns within 14 days (Trendyol terms)",
 handoffLi4: "Careful packaging for handmade items",
 handoffGo: "Go Now",
 careTitle: "{name} - Care & Size",
 careLead: "Tips to enjoy your handmade piece for years.",
 careWash: "Care",
 careSize: "Size reference",
 careSafety: "Safety",
 ok: "OK",
 },
 cookie: {
 title: "Cookie preferences",
 text: "Essential cookies run the site. Accept All saves your preference; third-party analytics are currently disabled.",
 link: "Privacy policy",
 linkSuffix: "for details.",
 essential: "Essential Only",
 accept: "Accept All",
 },
 sound: { on: "Mute sounds", off: "Enable sounds", label: "Sound" },
 palette: {
 peach: "Peach",
 sage: "Sage",
 gold: "Gold",
 cream: "Cream",
 blue: "Sky Blue",
 rose: "Dusty Rose",
 charcoal: "Charcoal",
 white: "White",
 },
 wizard: {
 eyebrow: "Your Dream Figure",
 title: "Custom Order Wizard",
 lead: "Design your figure in four steps. We'll receive your request by email or WhatsApp.",
 stepsLabel: "Order steps",
 stepFigure: "Figure",
 stepColor: "Color",
 stepSize: "Size",
 stepSummary: "Summary",
 figureTitle: "Choose figure type",
 figureLead: "Design a custom figure inspired by our collection characters.",
 figureGroup: "Figure type",
 harryPotter: "Harry Potter",
 hermione: "Hermione Granger",
 malefiz: "Maleficent",
 ronald: "Ronald Weasley",
 colorTitle: "Your colour palette",
 colorLead: "You can select up to 3 colours.",
 colorGroup: "Colour selection",
 colorSelected: "Selected: {value}",
 colorNone: "Selected: - ",
 sizeTitle: "Size",
 sizeLead: "Approximate sitting height (10-40 cm).",
 sizeLabel: "Size:",
 notesTitle: "Notes & summary",
 notesLead: "Add name, date or special details.",
 notesLabel: "Additional notes",
 notesPlaceholder: "E.g. pink ribbon, name embroidery...",
 disclaimer: "Custom orders may have different return terms as they are made to order.",
 mailSend: "Send via Email",
 waSend: "Send via WhatsApp",
 back: "Back",
 next: "Next",
 finish: "Complete Request",
 errFigure: "Please select a figure type.",
 errColor: "Select at least one colour.",
 ref: "Reference",
 figure: "Figure",
 colors: "Colours",
 size: "Size",
 notes: "Notes",
 mailSubject: "Custom Order - {ref} - {figure}",
 msgIntro: "Hello Amigura,",
 msgTitle: "My custom order request:",
 msgThanks: "Thank you.",
 msgRef: "Reference",
 msgFigure: "Figure",
 msgColors: "Colours",
 msgSize: "Size",
 msgNotes: "Notes",
 },
 thanks: {
 email: "Email",
 eyebrow: "Amigura",
 title: "Thank you for your order",
 lead:
 "Your package was prepared with care. This little figure left our studio with love - may it warm your memories for years.",
 careTitle: "Care tips",
 care1: "Cold wash (30C) or delicate cycle; use mild detergent.",
 care2: "Lay flat to dry; avoid tumble dryers.",
 care3: "Avoid prolonged direct sun to keep colours vibrant.",
 care4: "For small marks, a lightly damp cloth is enough.",
 socialTitle: "Follow us",
 socialLead: "Join us on social media for studio moments, new collections and custom order news.",
 socialNav: "Social media links",
 home: "Back to Collection",
 },
};
